
[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = true

# [[language]]
# name = "python"
# language-id = "python"
# #language-servers = ["ruff", "basedpyright"]

[[language]]

name = "python"
language-servers = ["ruff", "basedpyright"]
injection-regex = "py(thon)?"
file-types = ["py", "pyi", "py3", "pyw", "ptl", "rpy", "cpy", "ipy", "pyt", { glob = ".python_history" }, { glob = ".pythonstartup" }, { glob = ".pythonrc" }, { glob = "*SConstruct" }, { glob = "*SConscript" }, { glob = "*sconstruct" }]
shebangs = ["python", "uv"]
scope = "source.python"
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
auto-format = true
formatter = { command = "uvx", args = ["sh", "-c", "ruff check --fix - | ruff format -"] }
comment-token = "#"
indent = { tab-width = 4, unit = "    " }


[[grammar]]
name = "python"
source = { git = "https://github.com/tree-sitter/tree-sitter-python", rev = "4bfdd9033a2225cc95032ce77066b7aeca9e2efc" }

[language-server.basedpyright]
command = "uv"
args = ["run", "basedpyright-langserver", "--stdio"]

# [language-server.basedpyright.config]


[language-server.ruff]
command = "uvx"
args = ["ruff","server"]
environment = { "RUFF_TRACE" = "messages" }

[language-server.ruff.config.settings]
lineLength = 100

[language-server.ruff.config.settings.lint]
select = ["E4", "E7"]
preview = false

[language-server.ruff.config.settings.format]
preview = true

language-servers = ["ruff", "jedi", "pylsp"]
# TODO: pyls needs utf-8 offsets
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "python"
source = { git = "https://github.com/tree-sitter/tree-sitter-python", rev = "4bfdd9033a2225cc95032ce77066b7aeca9e2efc" }


[[language]]
name="rust"
formatter = { command = "rustfmt" }
auto-format = true

[language-server.rust-analyzer.config]
checkOnSave = {command = "clippy", extraArgs = ["--", "-W", "clippy::pedantic"]}
cargo = {allFeatures = true}
procMacro = {enable = true }
